### ISSUE TITLE
Causing issues on windows..

### ISSUE THREAD

**Issue by laggingreflex** [StreetStrider/repl.js#3]
I've installed it globally `npm install -g repl.js` but when I try to run `repl.js` it just opens a file `repl.js` in my SublimeText editor. 

I think the issue is that in windows, it's supposed to execute the `C:\Users\xxx\AppData\Roaming\npm\repl.js.cmd` file. But there also exists a `C:\Users\xxx\AppData\Roaming\npm\repl.js` file. And that's the file that's being opened in my text editor. I deleted that file and it worked for me.

I think maybe the `.js` in the module's name is causing this confusion for windows. I don't have much deeper understanding how global modules work, and how their "executables" files are generated but there are other modules that produce similar structure too (i.e. two files: `...\npm\babel` and `...\npm\babel.cmd`), and they all work just fine. The only thing different in this module is that it has a dot (.js) in its name, which I think is causing windows to open the `.js` file in a text editor instead of executing the `.js.cmd`

I haven't tried any other ".js" modules, I'll see if I can learn any more info from them. Like mean.js I think

[Windows 8.1]

**Comment by StreetStrider** [comment]
I believe, your's `.js` files is associated with Sublime Text editor. For instance, on my VM, I got error, since my `.js` files is associated with JScript (which is by default). However, I'm able to run `repl.js.cmd`. Is this work for you?

When I'm trying to locate `repl.js` and `repl.js.cmd` I got this:
```
C:\Program Files\ConEmu>where repl.js
C:\Program Files\nodejs\repl.js
C:\Program Files\nodejs\repl.js.cmd
C:\Users\Admin\AppData\Roaming\npm\repl.js
C:\Users\Admin\AppData\Roaming\npm\repl.js.cmd
```
```
C:\Program Files\ConEmu>where repl.js.cmd
C:\Program Files\nodejs\repl.js.cmd
C:\Users\Admin\AppData\Roaming\npm\repl.js.cmd
```
I think first found file will be in effect. In first case `C:\Program Files\nodejs\repl.js` is in effect, in second `C:\Program Files\nodejs\repl.js.cmd`.

**Comment by laggingreflex** [comment]
The problem is not the text editor or file associations actually, it's that Windows will invoke `npm\repl.js` instead of `npm\repl.js.cmd`. 

Like you noticed, the two files responsible for invoking the program via command-line are:

    C:\Users\Admin\AppData\Roaming\npm\repl.js
    C:\Users\Admin\AppData\Roaming\npm\repl.js.cmd

Consider another module **babel** for example, in its case the files would be 

    C:\Users\Admin\AppData\Roaming\npm\babel
    C:\Users\Admin\AppData\Roaming\npm\babel.cmd

On Windows `npm\babel.cmd` would take precedence, and on Linux, `npm\babel`. Note that `npm\babel` (and `npm\repl.js` correspondingly) are the shell script files meant for Linux. `npm\repl.js` is not actually a javascript file, but beacuse it *looks* like it, Windows invokes *it* instead of `npm\repl.js.cmd`. ***That's*** **the problem**. Only if I delete `npm\repl.js` things actually work fine (i.e. `npm\repl.js.cmd` gets invoked) otherwise `npm\repl.js` takes precedence in getting invoked (in whatever text editor) every time I try to run `repl.js` command from cmd.

**Comment by StreetStrider** [comment]
1. Can you just call `repl.js.cmd`?
2. If this does not satisfy you, then why? Do you want some shorter name to invoke or what?
3. If so, I can register another bin specially for windows, call it `repl-js`. This will allow to workaround this resolution preference issue and this name is the same length as `repl.js`.

**Comment by laggingreflex** [comment]
1. Yes! 

I actually only just now realized that I don't need to delete the file `npm/repl.js` ***if*** I *specifically* call `repl.js.cmd`. This could be the easiest fix. It would just require adding a caution to windows user in Readme.md that they need to use `repl.js.cmd` instead of `repl.js` (because usually windows users are just supposed to call `babel` instead of `babel.cmd` for example)

Or if it's possible in post-install scripts to actually delete the `npm/repl.js` on windows automatically? That's what I did as a workaround and so now I can just call `repl.js`

2. Being able to call just `repl.js` would be the ideal solution.

3. This could work too, but the above two sound better options now I guess.

**Comment by StreetStrider** [comment]
@laggingreflex, try `npm i -g repl.js@2.2.0-pre`. It contains `repljs` binary.

**Comment by StreetStrider** [comment]
I've also don't think removing something outside of a package is a good idea, even if it is a binary for this package. Even if I want to remove one of the binaries on windows this would be an issue, since it would require to hardcode [windows paths](https://docs.npmjs.com/files/folders) to search for and this would be not a 100%-solution if npm installed on other path.

**Comment by laggingreflex** [comment]
Right, good call. I like `repljs` solution. It works\* now, you have to type the command `repljs` instead of `repl.js`. It should be mentioned in readme.md for windows users. 

\* Although [that aux error is still present](https://github.com/StreetStrider/repl.js/issues/4#issuecomment-130727486).

**Comment by StreetStrider** [comment]
This is 20%-solution. Maybe this will drift away by itself, if npm improves this.
