### ISSUE TITLE
windows issues: aux.js is an invalid filename

### ISSUE THREAD

**Issue by laggingreflex** [StreetStrider/repl.js#4]
It seems windows doesn't like the filename ["aux.js" (among others)](http://google.com/search?q=windows+aux.js) which is the file `src/utilrepl/aux.js`. [Same bug here](https://github.com/jrburke/r.js/issues/249) was dealt with renaming it to pax.js

**Comment by StreetStrider** [comment]
@laggingreflex, wow, you're right, aux is a reserved filename indeed, just as other filenames like [con, comX, lptX & prn](http://stackoverflow.com/questions/122400/what-are-reserved-filenames-for-various-platforms). I can rename `src/utilrepl/aux.js` to other name, but I'm not sure it will solve the issue, since `repl.js` depends on other package `aux.js` which also has file with this name.

Well, I should investigate this issue on windows.

**Comment by StreetStrider** [comment]
Hmm, I can't repro it. I'm able to resolve this filename:
```js
js > require.resolve('C:\\Program Files\\nodejs\\node_modules\\repl.js\\node_modules\\aux.js')
'C:\\Program Files\\nodejs\\node_modules\\repl.js\\node_modules\\aux.js\\index.js'
```

**Comment by laggingreflex** [comment]
Maybe it works on Wine or Virtual box on Linux but I can't create anything, file or folder, named aux.js. Not even via Git Shell.

    C:\test>echo hi > aux.js
    The system cannot find the file specified.
    C:\test>mkdir aux.js
    The directory name is invalid.



    $ mkdir aux.js
    mkdir: cannot create directory `aux.js': Not a directory
    $ echo hi > aux.js
    sh.exe": aux.js: No such file or directory

Even `git clone` refuses to checkout the file `aux.js`

    C:\test>git clone https://github.com/StreetStrider/repl.js.git
    Cloning into 'repl.js'...
    remote: Counting objects: 757, done.
    remote: Compressing objects: 100% (10/10), done.
    Receiving objects: 100% (757/757), 80.72 KiB | 34.00 KiB/s, done.
    Resolving deltas:   2% (10/462)
    Resolving deltas: 100% (462/462), done.
    Checking connectivity... done.
    error: unable to create file src/utilrepl/aux.js (No such file or directory)
    fatal: unable to checkout working tree
    warning: Clone succeeded, but checkout failed.
    You can inspect what was checked out with 'git status'
    and retry the checkout with 'git checkout -f HEAD'

**Comment by StreetStrider** [comment]
@laggingreflex, well, this time I reproduced issue if I'm using git (just like in your's example), but when I install package via npm everything works ok. Maybe npm has some workaround for this. i.e. I have the same error you do when I try to clone `repl.js`, but I can install package from registry and I have `aux.js` on my disk and everything works fine: I can `require.resolve` it, I have `aux` object in globals etc.

I'm seeing only one workaround for this:
```js
try { … = require('./src/utilrepl/aux.js'); } catch (e) …
```
So, on windows this will ignore non-existent file and proceed. Any thoughts? Maybe you have some better workaround in mind?

**Comment by laggingreflex** [comment]
npm too doesn't install the file for me either. That's actually how the first time I discovered this bug.

About the try-catch, wouldn't that just **not** include aux.js altogether? What about its contents/methods being used elsewhere (which would've been the reason it was required in the first place)? 

I can only think of renaming the file, ax.js axillary.js … which is what I did as a workaround, I renamed the file to pax.js and changed the code that required it.

**Comment by StreetStrider** [comment]
@laggingreflex, I've installed node + npm on real windows and had the same state of things:
1. I can't create `aux` or `aux.js` by hand
2. npm is able to do this
Check you npm version, please. I suspect you have and old version (maybe one of `npm@1`) which somehow not able to install `aux.js`.

**Comment by laggingreflex** [comment]
Are you able to run it though? Or can you open it? I have npm@2.11. It does create the file somehow but any way of accessing it results in error, either `type` command in cmd or opening it in notepad both result in errors. 

[![src]][src]


[src]: http://i.imgur.com/urn46YV.png

**Comment by laggingreflex** [comment]
So I reinstalled it, but still the error

    C:\test>npm i -g repl.js@2.2.0-pre
    C:\Users\Admin\AppData\Roaming\npm\repl.js -> C:\Users\Admin\AppData\Roaming\npm\node_modules\repl.js\run\repl
    C:\Users\Admin\AppData\Roaming\npm\repljs -> C:\Users\Admin\AppData\Roaming\npm\node_modules\repl.js\run\repl
    repl.js@2.2.0-pre C:\Users\Admin\AppData\Roaming\npm\node_modules\repl.js
    ├── minimist@1.1.3
    ├── aux.js@2.5.1
    ├── promise@7.0.4 (asap@2.0.3)
    ├── console-ultimate@2.7.0 (pretty-hrtime@1.0.0, object-path@0.9.2, lodash.repeat@3.0.1, lodash.merge@3.3.2, trace@1.2.0, clarify@1.0.5, lodash.find@3.2.1)
    └── cli-color@1.0.0 (ansi-regex@1.1.1, d@0.1.1, timers-ext@0.1.0, es6-iterator@0.1.3, memoizee@0.3.9, es5-ext@0.10.7)



    C:\test>repljs
    module.js:334
        throw err;
              ^
    Error: Cannot find module './aux'
        at Function.Module._resolveFilename (module.js:332:15)
        at Function.Module._load (module.js:282:25)
        at Module.require (module.js:361:17)
        at require (module.js:380:17)
        at Object.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\repl.js\src\utilrepl\index.js:10:7)
        at Module._compile (module.js:426:26)

**Comment by StreetStrider** [comment]
@laggingreflex,
> Are you able to run it though? Or can you open it?

Node able to run it, i.e. repl starts ok and I got fully functional `aux` object in its globals. However, I cannot open `aux.js` for instance in Sublime Text.

What happens when you rename `aux.js`to `ax.js`? Does repl starts? I wonder, because except `src/utilrepl/aux.js` there's **whole package** `node_modules/aux.js`. And I worry that simple renaming file won't do the trick, because then package starts fail.

**Comment by laggingreflex** [comment]
I had **iojs (2.3)** installed, which I temporarily disabled and switched back to **node 0.12** and things worked fine! But since we're gonna be moving forward towards higher versions of node, I don't think this should be considered a solution.

About renaming aux.js, I can't, any way to access or change it [causes error][scr]. I had to create a new file and copy contents from [source][aux.js].
The folder `aux.js` (the module) is also behaving strangely. It does exist and has the proper files and folders structure inside it, but I [can't access any files][scr2].



[scr]: http://i.imgur.com/PwfjnCx.png
[scr2]: http://i.imgur.com/RZ7VJas.png
[aux.js]: https://github.com/StreetStrider/repl.js/blob/master/src/utilrepl/aux.js

**Comment by StreetStrider** [comment]
> Can you test with iojs? Because I think since we're going to be moving towards iojs anyways, solution should be aimed to work with that.

I will test it in io.js, but I don't think we can do anything. If io.js/Node.js merging will fix this issue, it will fix it. If no, then we cannot fix it too.

**Comment by StreetStrider** [comment]
@laggingreflex, looks like I'm able to run this either:
```
> "C:\Program Files\iojs\iojs.exe" "C:\Program Files\nodejs\node_modules\repl.js\run\repl"
```

**Comment by StreetStrider** [comment]
@laggingreflex, try `repl.js@2.2.0-pre2` by yourself. I've renamed file to `ax.js`.

**Comment by laggingreflex** [comment]
It works. (with same iojs @2.3, will check with @3 later)

As a sidenote, the module `aux.js` works too, I guess as long as it's a folder (and not a file) it'll work.

**Comment by StreetStrider** [comment]
I got the same feeling about directory. Well, I'll retain this workaround and post a new release.

**Comment by animesharma** [comment]
Thanks for this! I was having a similar issue somewhere in my project(unrelated). Renaming Aux.js there worked!

**Comment by amit3202** [comment]
Create file by any name, then rename it as Aux.js in visual studio it will work.

**Comment by Fauzan-Khot** [comment]
> Create file by any name, then rename it as Aux.js in visual studio it will work.

it's not working
