### ISSUE TITLE
Assign resolved value with a variable

### ISSUE THREAD

**Issue by heycalmdown** [StreetStrider/repl.js#7]
I have to say thank you and this project is brilliant. This is what I want to have at someday!
It make node's REPL look like nearly python's.

A little missing point is that assigning the resolved value from a Promise with a variable. How do you handle this on your use-case?

Use recent evaluated value(_)?

```Javascript
> request.get('http://blahblah.com/a/b/c');
> const res = _;
> console.log(res.body);
```

**Comment by StreetStrider** [comment]
@heycalmdown, hello. As far as I understood, you want promise resolution to be stored in `_`, just like regular expression result. Correct?

**Comment by heycalmdown** [comment]
no. The shell stores last result into _, so I could use the result with _. But I wanted know how do *you* usually work with. :)

**Comment by StreetStrider** [comment]
I usually just run expressions which return promises. If I need it again it is much simpler to run it again (in most cases). I use intermediate `_` pretty rarely, mostly for some arithmetic calculations. 

Sometimes I want to store promise-like object and do not capture it in my REPL. In this case I can do:
 `[ request.get('http://blahblah.com/a/b/c') ]`, putting promise in array prevents it from unwrapping. Later I can manually «unwrap» it by `_[0]`.

**Comment by heycalmdown** [comment]
okay. thanks for sharing.
